### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by x0n4d0** [x0n4d0/tuxwizard#1]
- [x] Refactor older project

- [x] Define project pattern

- [x] Create test/ directory
